import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: 'Welcome to Khrimisay',
    template: '%s | Khrimisay',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}


        <Script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></Script>
        <Script src="https://code.jquery.com/jquery-1.12.4.js"></Script>
        <Script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></Script>

        <Script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></Script>
        <Script src="https://code.jquery.com/jquery-1.11.3.min.js"></Script>

        <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></Script>


        <Script src="https://unpkg.com/@yaireo/tagify"></Script>
        <Script src="https://unpkg.com/%40yaireo/tagify%404.17.8/dist/tagify.polyfills.min.js"></Script>


        <Script src="https://cdn.tiny.cloud/1/invalid-origin/tinymce/5.10.7-133/tinymce.min.js"></Script>
        <Script src="/assets/js/common.js"></Script>
      </body>
    </html>
  )
}
